name: Shifting Units
favicon: null
layout_spectrum: 0.74047
typography_spectrum: 0.9614129683468491
title: "Ecommerce isn't rocket science, it's just shifting units."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#a4b5bf'
    - '#5a6169'
    - '#090e14'
    - '#dcd2d0'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.8380021320190281
  rhythmicContrast: 0.5
purpose: []
